Repository gnosis/gp-v2-contracts, pull requests merged in 2020-12, with the labels that each got.

#202 rename processTrade to computeTradeExecution
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green, trivial

#203 Fix prices
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#207 Only use fixed fees
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#206 Check limit price when computing trade execution
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#208 Do not transfer full fees for partial orders
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#212 Check order has not expired
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#215 Frist npm release to depend on package in gp-v2-services
  .eslintrc.js
  .gitignore
  bench/decodeTrade.ts
  package.json
  tsconfig.json
Labels: merge when green

#213 Check filled amounts
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#222 Bump to NodeJS 14
  .github/workflows/CI.yml
  .mergify.yml
  yarn.lock
Labels: trivial

#214 New uid format
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/index.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#221 Refactor transfers into executed trade struct
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
  src/contracts/test/NonStandardERC20.sol
  test/GPv2AllowanceManager.test.ts
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green

#225 Implement method to transfer out executed buy amounts to EOA orders
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green

#227 Refactor test encoding
  src/contracts/GPv2Settlement.sol
  test/GPv2AllowanceManager.test.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
  test/encoding.ts
Labels: merge when green

#235 Use ethers human redable ABI instead of compiling test contract
  src/contracts/test/NonStandardERC20.sol
  test/GPv2AllowanceManager.test.ts
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green, trivial

#241 [Easy] Two Forgotten suggestions from #224
  src/contracts/GPv2Settlement.sol
  test/encoding.ts
Labels: merge when green

#233 Refactor order UID
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/encoding.ts
Labels: merge when green

#234 Trade event
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#247 Split TS library into smaller modules
  src/ts/deploy.ts
  src/ts/index.ts
  src/ts/order.ts
  src/ts/reader.ts
  src/ts/settlement.ts
Labels: merge when green, trivial

#228 Eoa order settlement
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.e2e.ts
  test/GPv2Settlement.test.ts
  test/deployment.e2e.ts
  test/fixture.ts
Labels: merge when green

#248 Move e2e tests into subdirectory
  test/e2e/deployment.test.ts
  test/e2e/fixture.ts
  test/e2e/wineOilMarket.test.ts
Labels: merge when green, trivial

#249 refactor deterministic address computation
  src/deploy/001_authenticator.ts
  src/deploy/002_settlement.ts
  src/ts/deploy.ts
Labels: merge when green

#236 Encode fee discount
  bench/decodeTrade.ts
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/wineOilMarket.test.ts
  test/encoding.ts
Labels: merge when green

#244 Apply fee discount
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#256 Refactor ethers typings extensions
  bench/decodeTrade.ts
  src/ts/index.ts
  src/ts/order.ts
  src/ts/settlement.ts
  src/ts/types/ethers.ts
  test/GPv2Settlement.test.ts
  test/e2e/wineOilMarket.test.ts
  tsconfig.json
  typings/ethers/index.d.ts
Labels: merge when green, trivial

#257 New rinkeby deployment and npm package: 0.0.1-alpha.2
  package.json
Labels: merge when green

#250 Add interaction encoding and decoding
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/ts/index.ts
  src/ts/interaction.ts
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/encoding.ts
Labels: merge when green

#258 Make ethers a peer dependency
  package.json
Labels: merge when green, trivial

#261 use enum order kind
  bench/decodeTrade.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/order.ts
  src/ts/settlement.ts
  test/encoding.ts
Labels: merge when green

#262 Bump up deployment gas limit
  src/deploy/002_settlement.ts
Labels: merge when green

#265 adjust main and types path in module
  package.json
Labels: merge when green, trivial

#267 Package version bump to 0.0.1-alpha.4
  networks.json
  package.json
Labels: merge when green

#274 Allows to verify contracts on etherscan, replaces https://github.com/gnosis/gp-v2-contracts/pull/255
  README.md
  deployments/rinkeby/GPv2Settlement.json
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/interfaces/GPv2Authentication.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/ownership/CustomInitiallyOwnable.sol
  src/contracts/reader/AllowListStorageReader.sol
  src/contracts/test/EventEmitter.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
Labels: merge when green

#282 Add script to manage solver authentication
  README.md
  hardhat.config.ts
  package.json
  src/tasks/solvers.ts
  src/ts/deploy.ts
Labels: merge when green

#285 v0.0.1-alpha.8
  deployments/rinkeby/GPv2AllowListAuthentication.json
  deployments/rinkeby/GPv2Settlement.json
  networks.json
  package.json
Labels: merge when green

#284 Isolate function requiring build artifacts
  src/ts/deploy.ts
  src/ts/deterministic_address.ts
  test/e2e/deployment.test.ts
Labels: merge when green

#287 Mainnet Deployment (alpha.10 release)
  deployments/mainnet/.chainId
  deployments/mainnet/GPv2AllowListAuthentication.json
  deployments/mainnet/GPv2Settlement.json
  networks.json
  package.json
Labels: merge when green

#288 xDAI deployment (v0.0.1-alpha.11)
  deployments/xdai/.chainId
  deployments/xdai/GPv2AllowListAuthentication.json
  deployments/xdai/GPv2Settlement.json
  networks.json
  package.json
Labels: merge when green
