Repository gnosis/gp-v2-contracts, pull requests merged in 2020-09, with the labels that each got.

#29 Make use of ESLint import plugin
  .eslintrc.js
  src/js/orders.spec.ts
  test/PreAMMBatcher-e2e.ts
  test/PreAMMBatcher.spec.ts
  test/resources/index.ts
  test/resources/testExamples.ts
Labels: merge when green

#28 Initial buidler setup
  .gitignore
  README.md
  buidler.config.ts
  package.json
  test/PreAMMBatcher-e2e.ts
  test/PreAMMBatcher.spec.ts
  tsconfig.json
  typings/buidler/index.d.ts
  yarn.lock
Labels: merge when green

#36 Use the same solidty version pragma for all contracts
  src/contracts/PreAMMBatcher.sol
  src/contracts/test/ERC20Mintable.sol
Labels: merge when green, trivial

#35 Enforce frozen yarn lockfile
  .github/workflows/CI.yml
  yarn.lock
Labels: merge when green, trivial

#37 Use OpenZeppelin preset ERC20 mintable contract
  test/PreAMMBatcher-e2e.ts
Labels: merge when green, trivial

#40 Fix leftover ERC20Mintable.sol references
  src/contracts/test/ERC20Mintable.sol
  test/PreAMMBatcher.spec.ts
Labels: merge when green, trivial

#39 Restructure order decoding
  src/contracts/PreAMMBatcher.sol
  test/PreAMMBatcher-e2e.ts
  test/PreAMMBatcher.spec.ts
Labels: merge when green

#21 Sorted Order Verifier Method
  src/contracts/PreAMMBatcher.sol
  src/contracts/test/PreAMMBatcherTestInerface.sol
  test/PreAMMBatcher.spec.ts
Labels: merge when green

#32 Use buidler test harness
  package.json
  src/js/orders.spec.ts
  test/PreAMMBatcher.e2e.ts
  test/PreAMMBatcher.test.ts
  test/resources/index.ts
  yarn.lock
Labels: merge when green

#51 Update license copyright and text
  LICENSE
Labels: documentation, merge when green

#52 Remove old waffle and mocha files
  .mocharc.json
  test/mocha.opts
  waffle.json
Labels: merge when green

#53 add solhint linting
  .solhint.json
  package.json
  src/contracts/PreAMMBatcher.sol
  src/contracts/test/PreAMMBatcherTestInterface.sol
  test/PreAMMBatcher.test.ts
  yarn.lock
Labels: merge when green
