Repository gnosis/gp-v2-contracts, pull requests merged in 2020-11, with the labels that each got.

#112 implement order decoding
  package.json
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/index.ts
  test/GPv2Settlement.test.ts
  typings/ethers/index.d.ts
Labels: merge when green

#134 cleanup settlement contract
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green, trivial

#135 Migrate from buidler to hardhat
  hardhat.config.ts
  package.json
  test/GPv2Settlement.test.ts
  test/PreAMMBatcher.e2e.ts
  test/PreAMMBatcher.test.ts
  typings/buidler/index.d.ts
  yarn.lock
Labels: merge when green, trivial

#136 Remove `PreAMMBatcher`
  package.json
  src/contracts/PreAMMBatcher.sol
  src/contracts/libraries/Math.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/PreAMMBatcherTestInterface.sol
  src/js/orders.spec.ts
  src/ts/index.ts
  test/PreAMMBatcher.e2e.ts
  test/PreAMMBatcher.test.ts
  test/resources/index.ts
  test/resources/models.ts
  test/resources/orderCreation.ts
  test/resources/testExamples.ts
Labels: merge when green, trivial

#137 Add order encoding API
  src/ts/index.ts
Labels: merge when green

#117 N-Dimentional Packed Order Decoding.
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  test/GPv2Encoding.test.ts
Labels: merge when green

#141 use EIP-712 domain separator
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/index.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#142 Use eth_signMessage signature scheme
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
Labels: merge when green

#145 Alternate implementation for eth_signTypedData support
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
  typings/ethers/index.d.ts
Labels: merge when green

#156 Refactor order struct into trade and order
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
Labels: merge when green

#157 Add standard networks to Hardhat config
  hardhat.config.ts
  package.json
  yarn.lock
Labels: merge when green

#160 Upgrade to Solidity v0.7.5
  .solhint.json
  hardhat.config.ts
  package.json
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  yarn.lock
Labels: trivial

#161 Add allowance manager implementation
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/test/NonStandardERC20.sol
  test/GPv2AllowanceManager.test.ts
Labels: merge when green

#175 Use constants for signing domain parameters
  src/contracts/GPv2Settlement.sol
Labels: merge when green, trivial

#162 Assembly calldata reading.
  bench/decodeTrade.ts
  package.json
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#168 Remove `typeHash` field from `Order` struct
  src/contracts/libraries/GPv2Encoding.sol
  test/GPv2Encoding.test.ts
Labels: merge when green

#173 Rename 'nonce' to 'appData'
  bench/decodeTrade.ts
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
Labels: merge when green, trivial

#176 Deploy an allowance manager with the settlement contract
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2AllowanceManager.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#181 Add function to compute allowance manager address off-chain
  src/ts/index.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#183 Enable Solidity optimizer
  hardhat.config.ts
Labels: merge when green, trivial

#180 Add utility methods for slicing encoded trades
  bench/decodeTrade.ts
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  test/GPv2Encoding.test.ts
Labels: merge when green

#186 Define initial authenticator owner in constructor
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/ownership/CustomInitiallyOwnable.sol
  test/GPv2AllowListAuthenticator.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#184 Initial order processing implementation.
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/index.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#189 #184 Missing Comment
  src/contracts/GPv2Settlement.sol
Labels: trivial

#190 Migration scripts
  README.md
  hardhat.config.ts
  package.json
  src/deploy/001_authenticator.ts
  src/deploy/002_settlement.ts
  src/ts/deploy.ts
  test/GPv2Settlement.test.ts
  test/bytecode.ts
  test/deployment.e2e.ts
  yarn.lock
Labels: merge when green
