Repository gnosis/gp-v2-contracts, pull requests merged in 2021-02, with the labels that each got.

#396 Storage Accessible Settlement
  src/contracts/GPv2Settlement.sol
  src/contracts/reader/SettlementStorageReader.sol
  src/deploy/002_settlement.ts
  src/ts/reader.ts
  test/SettlementStorageReader.test.ts
Labels: merge when green

#384 ABI encoded interactions
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Interaction.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2InteractionTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/NonPayable.sol
  src/ts/interaction.ts
  src/ts/settlement.ts
  test/AllowListStorageReader.test.ts
  test/GPv2Encoding.test.ts
  test/GPv2Interaction.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#385 ABI Encode order UIDs for storage refunds
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2OrderTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Order.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#388 Move order struct to library
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2OrderTestInterface.sol
  src/ts/order.ts
  test/GPv2Encoding.test.ts
  test/GPv2Order.test.ts
  test/encoding.ts
Labels: merge when green

#390 ABI encoded trades.
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Signing.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/test/GPv2OrderTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/SettlementStorageReader.test.ts
  test/e2e/contractOrdersWithGnosisSafe.test.ts
  test/encoding.ts
Labels: merge when green

#399 Convert signing library to a mixin
  hardhat.config.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
Labels: merge when green

#351 Upgradable Authenticator
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/ownership/CustomInitiallyOwnable.sol
  src/contracts/test/GPv2AllowListAuthenticationV2.sol
  src/deploy/001_authenticator.ts
  src/ts/deploy.ts
  src/ts/index.ts
  src/ts/proxy.ts
  test/AllowListStorageReader.test.ts
  test/GPv2AllowListAuthenticator.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/deployment.test.ts
  test/e2e/upgradeAuthenticator.test.ts
Labels: merge when green

#398 Add test verifying deterministic deployment of proxy
  src/ts/deploy.ts
  test/e2e/deployment.test.ts
Labels: merge when green

#402 Unify signing schemes to all use EIP-712 signing hash
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  src/ts/order.ts
  src/ts/sign.ts
  test/GPv2Order.test.ts
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
  test/e2e/contractOrdersWithGnosisSafe.test.ts
  test/e2e/orderRefunds.test.ts
Labels: merge when green

#406 Remove free memory pointer manipulation as has little to no effect.
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  test/GPv2Signing.test.ts
Labels: merge when green, trivial

#401 Add presign scheme
  bench/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/reader/SettlementStorageReader.sol
  src/ts/order.ts
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Order.test.ts
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
  test/GPv2Trade.test.ts
  test/SettlementStorageReader.test.ts
  test/e2e/orderRefunds.test.ts
Labels: merge when green

#407 Allow changing manager
  bench/fixture.ts
  hardhat.config.ts
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/libraries/GPv2EIP1967.sol
  src/contracts/test/GPv2AllowListAuthenticationTestInterface.sol
  src/deploy/001_authenticator.ts
  src/tasks/solvers.ts
  src/ts/proxy.ts
  test/GPv2AllowListAuthenticator.test.ts
  test/e2e/0xTrade.test.ts
  test/e2e/burnFees.test.ts
  test/e2e/buyEth.test.ts
  test/e2e/contractOrdersWithGnosisSafe.test.ts
  test/e2e/deployment.test.ts
  test/e2e/ercPermit.test.ts
  test/e2e/fixture.ts
  test/e2e/orderRefunds.test.ts
  test/e2e/uniswapTrade.test.ts
  test/e2e/upgradeAuthenticator.test.ts
  test/e2e/wineOilMarket.test.ts
Labels: merge when green

#409 Differentiate between classes of order refunds
  bench/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
  test/e2e/orderRefunds.test.ts
  test/encoding.ts
Labels: merge when green

#413 Combine order hashing methods into one.
  src/contracts/libraries/GPv2Order.sol
  src/contracts/mixins/GPv2Signing.sol
  src/contracts/test/GPv2OrderTestInterface.sol
  src/contracts/test/GPv2SigningTestInterface.sol
  src/ts/order.ts
  src/ts/sign.ts
  test/GPv2Order.test.ts
  test/GPv2Signing.test.ts
  test/e2e/contractOrdersWithGnosisSafe.test.ts
Labels: merge when green

#410 Add batched Uniswap benchmarks
  bench/fixture.ts
  bench/uniswap/fixture.ts
  bench/uniswap/index.ts
  package.json
  yarn.lock
Labels: merge when green

#416 Cleanup documentation
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Interaction.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/libraries/GPv2SafeERC20.sol
  test/GPv2Interaction.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green, trivial

#417 More ASM 🙈: Optimized Safe ERC20 library.
  src/contracts/libraries/GPv2SafeERC20.sol
  test/ERC20.ts
  test/GPv2SafeERC20.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green

#420 started adding documentation
  README.md
  docs/architecture.md
  docs/images/architecture.png
  docs/index.md
Labels: documentation, merge when green

#421 Assembly for calling interaction
  src/contracts/libraries/GPv2Interaction.sol
Labels: merge when green

#435 Bump @gnosis.pm/util-contracts from 3.0.1-solc-7 to 3.1.0-solc-7
  package.json
  yarn.lock
Labels: merge when green, trivial

#430 Reach full coverage
  src/contracts/mixins/GPv2Signing.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#427 Emit presignature event
  src/contracts/mixins/GPv2Signing.sol
  test/GPv2Signing.test.ts
Labels: merge when green

#437 Compute actual receiver when recovering order
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/mixins/GPv2Signing.sol
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green

#438 Add allowance manager method for direct transfers
  src/contracts/GPv2AllowanceManager.sol
  test/GPv2AllowanceManager.test.ts
Labels: merge when green

#439 Implement single trade execution
  src/contracts/GPv2Settlement.sol
  src/contracts/test/BalanceOf.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#440 Implement single trade settlement
  bench/fixture.ts
  bench/single.ts
  package.json
  src/contracts/GPv2Settlement.sol
  src/deploy/002_settlement.ts
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
  test/e2e/singleOrder.test.ts
Labels: merge when green

#450 Yarn package upgrade
  yarn.lock
Labels: merge when green, trivial

#451 Use dedicated OZ solc-7 package
  package.json
  yarn.lock
Labels: merge when green, trivial

#456 Revert "Bump @openzeppelin/contracts from 3.4.0-solc-0.7 to 3.4.0"
  package.json
  yarn.lock
Labels: trivial

#461 Test: fast path reverts if order was partially filled
  test/GPv2Settlement.test.ts
Labels: merge when green

#467 Remove single trade settlement
  bench/fixture.ts
  bench/single.ts
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  test/GPv2AllowanceManager.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/singleOrder.test.ts
Labels: merge when green
