Repository gnosis/gp-v2-contracts, pull requests merged in 2021-05, with the labels that each got.

#617 Refactor common functions outside of single tasks
  src/tasks/decode.ts
  src/tasks/solvers.ts
  src/tasks/ts/deployment.ts
  src/tasks/ts/erc20.ts
Labels: merge when green

#612 Fix pasting of long lines when decoding calldata
  src/tasks/decode.ts
Labels: merge when green

#616 Add new Balancer V2 deployements
  balancer/Authorizer.json
  balancer/Vault.json
  balancer/networks.json
Labels: merge when green

#618 Extract table logic to own file
  src/tasks/decode.ts
  src/tasks/ts/table.ts
Labels: merge when green

#619 Add withdraw task
  package.json
  src/tasks/index.ts
  src/tasks/withdraw.ts
Labels: merge when green

#624 Test solvers task
  hardhat.config.ts
  test/tasks/solvers.test.ts
Labels: merge when green

#623 Update to latest balancer vault
  balancer/test/MockPool.json
  bench/fixture.ts
  bench/index.ts
  bench/uniswap/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/GPv2VaultRelayer.sol
  src/contracts/interfaces/IVault.sol
  src/contracts/libraries/GPv2Transfer.sol
  src/deploy/002_settlement.ts
  src/ts/swap.ts
  src/ts/vault.ts
  test/GPv2Settlement.test.ts
  test/GPv2Transfer.test.ts
  test/GPv2VaultRelayer.test.ts
  test/balancer.ts
  test/e2e/balancer/.version
  test/e2e/balancer/Authorizer.json
  test/e2e/balancer/MockPool.json
  test/e2e/balancer/Vault.json
  test/e2e/balancerSwap.test.ts
  test/e2e/buyEth.test.ts
  test/e2e/fixture.ts
  test/e2e/internalBalances.test.ts
Labels: merge when green

#629 Version bump to `0.1.0`
  package.json
Labels: merge when green, trivial

#630 Add option to leave leftovers when withdrawing
  src/tasks/withdraw.ts
Labels: merge when green

#627 Change trade type to be compatible with ABI decode
  src/tasks/decode.ts
  src/ts/settlement.ts
Labels: merge when green

#647 Clarify single transfer differences
  src/contracts/GPv2VaultRelayer.sol
  src/contracts/libraries/GPv2Transfer.sol
  src/contracts/test/GPv2TransferTestInterface.sol
  test/GPv2Transfer.test.ts
Labels: merge when green, trivial

#648 Include audit report
  audits/GnosisProtocolV2May2021.pdf
Labels: trivial
