Repository gnosis/gp-v2-contracts, pull requests merged in 2021-01, with the labels that each got.

#308 Encode signing scheme when generating signature
  src/ts/order.ts
  src/ts/settlement.ts
Labels: merge when green

#309 Encode signature as r||s||v
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/order.ts
  test/GPv2Encoding.test.ts
Labels: merge when green

#310 Refactor deterministic deployment address code
  package.json
  src/ts/deploy.ts
  src/ts/deterministic_address.ts
  test/e2e/deployment.test.ts
Labels: merge when green

#312 Implement free order storage for gas refunds
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#318 Bump Solidity to v0.7.6
  hardhat.config.ts
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/interfaces/GPv2Authentication.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/ownership/CustomInitiallyOwnable.sol
  src/contracts/reader/AllowListStorageReader.sol
  src/contracts/test/EventEmitter.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
  test/bytecode.ts
Labels: merge when green

#316 Buy ETH
  package.json
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
  src/ts/order.ts
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
  test/e2e/buyEth.test.ts
  yarn.lock
Labels: merge when green

#317 Use more flavourful salt
  src/ts/deploy.ts
Labels: merge when green, trivial

#314 Implement method for claiming order gas refunds
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/order.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#319 Claim gas refunds from settlement function
  src/contracts/GPv2Settlement.sol
  src/ts/order.ts
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
  test/e2e/orderRefunds.test.ts
Labels: merge when green

#307 update SDPX to use LGPL 3 or newer identifier
  README.md
  deployments/rinkeby/GPv2AllowListAuthentication.json
  deployments/rinkeby/GPv2Settlement.json
  networks.json
  package.json
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/interfaces/GPv2Authentication.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/ownership/CustomInitiallyOwnable.sol
  src/contracts/reader/AllowListStorageReader.sol
  src/contracts/test/EventEmitter.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/contracts/test/GPv2TradeExecutionTestInterface.sol
Labels: merge when green

#313 Implement decoding packed order UIDs
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  test/GPv2Encoding.test.ts
Labels: merge when green

#326 Make authenticator public
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: trivial

#325 add event for invalidated orders
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#335 Fix contract documentation
  src/contracts/GPv2Settlement.sol
Labels: merge when green, trivial

#337 emit settlement event
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#334 Encode interaction Ether value
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/EventEmitter.sol
  src/ts/interaction.ts
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#323 implemented basic gas benchmarking for settlement
  bench/decodeTrade.ts
  bench/fixture.ts
  bench/index.ts
  package.json
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#336 Emit Interaction log
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#339 Add hardhat script for gas tracing.
  bench/fixture.ts
  bench/trace/gas.ts
  bench/trace/hook/index.ts
  bench/trace/hook/register.ts
  bench/trace/index.ts
  package.json
  yarn.lock
Labels: merge when green

#342 Settlement "Preparations"
  bench/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/test/ERC20Permit.sol
  src/ts/interaction.ts
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
  test/e2e/buyEth.test.ts
  test/e2e/ercPermit.test.ts
  test/e2e/orderRefunds.test.ts
  test/e2e/uniswapTrade.test.ts
  test/e2e/wineOilMarket.test.ts
Labels: merge when green

#348 Additional benches
  bench/index.ts
Labels: merge when green, trivial

#344 Extended trace bench
  bench/trace/gas.ts
  bench/trace/hook/register.ts
  bench/trace/index.ts
Labels: merge when green

#349 Add benchmark comparison script
  bench/compare.sh
  package.json
Labels: merge when green

#352 Settlement Post-Interactions
  bench/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/ts/interaction.ts
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/burnFees.test.ts
  test/e2e/buyEth.test.ts
  test/e2e/ercPermit.test.ts
  test/e2e/orderRefunds.test.ts
  test/e2e/uniswapTrade.test.ts
  test/e2e/wineOilMarket.test.ts
Labels: merge when green

#346 Custom safe erc20
  src/contracts/libraries/GPv2SafeERC20.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/test/GPv2SafeERC20TestInterface.sol
  test/ERC20.ts
  test/GPv2TradeExecution.test.ts
  test/e2e/GPv2SafeERC20.test.ts
Labels: merge when green

#361 [Easy] Rename Error message on invalid fee discount
  src/contracts/GPv2Settlement.sol
  test/GPv2Settlement.test.ts
Labels: merge when green

#362 [nit] Moving struct declarations into own group
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2TradeExecution.sol
Labels: merge when green

#355 Set up variable-length trade decoding
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/test/GPv2EncodingTestInterface.sol
  src/ts/settlement.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#364 E2e 0x integration
  package.json
  src/ts/order.ts
  test/e2e/0xTrade.test.ts
  test/e2e/zero-ex/index.ts
  test/e2e/zero-ex/v2/index.ts
  yarn.lock
Labels: merge when green

#371 Bench comparisons defaults to merge base
  bench/compare.sh
Labels: merge when green

#365 Separate signature schemes
  bench/fixture.ts
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Signing.sol
  src/ts/index.ts
  src/ts/order.ts
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/0xTrade.test.ts
  test/e2e/burnFees.test.ts
  test/e2e/buyEth.test.ts
  test/e2e/ercPermit.test.ts
  test/e2e/orderRefunds.test.ts
  test/e2e/uniswapTrade.test.ts
  test/e2e/wineOilMarket.test.ts
Labels: merge when green

#369 EIP-1271 contract signature
  src/contracts/GPv2Settlement.sol
  src/contracts/interfaces/GPv2EIP1271.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/contracts/libraries/GPv2Signing.sol
  src/contracts/test/StateChangingERC1271.sol
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
Labels: merge when green

#375 End to end test: trading with a Gnosis Safe
  hardhat.config.ts
  package.json
  src/contracts/test/GnosisSafeERC1271Fallback.sol
  test/e2e/contractOrdersWithGnosisSafe.test.ts
  yarn.lock
Labels: merge when green

#376 Add receiver field to order
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/order.ts
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Encoding.test.ts
  test/GPv2SafeERC20.test.ts
  test/e2e/0xTrade.test.ts
  test/encoding.ts
Labels: merge when green

#377 Send funds to receiver
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  test/GPv2Settlement.test.ts
  test/GPv2TradeExecution.test.ts
  test/encoding.ts
Labels: merge when green

#380 full size app data and fee discount
  bench/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Encoding.sol
  src/ts/order.ts
  src/ts/settlement.ts
  src/ts/sign.ts
  test/GPv2Encoding.test.ts
  test/GPv2Settlement.test.ts
  test/e2e/uniswapTrade.test.ts
  test/encoding.ts
Labels: merge when green

#383 Edge case: invalid transaction encoding
  test/GPv2Encoding.test.ts
Labels: merge when green

#387 Add missing yargs dependency
  package.json
  yarn.lock
Labels: merge when green, trivial
