Repository gnosis/gp-v2-contracts, pull requests merged in 2021-03, with the labels that each got.

#445 Implement gas refunds as an interaction.
  .prettierignore
  bench/single.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
  test/e2e/orderRefunds.test.ts
  test/encoding.ts
Labels: merge when green

#471 Add benchmarks for optimal refund batching
  bench/single.ts
Labels: merge when green

#478 Remove fee discount
  bench/fixture.ts
  bench/uniswap/fixture.ts
  src/contracts/GPv2Settlement.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/test/GPv2SettlementTestInterface.sol
  src/ts/settlement.ts
  test/GPv2Settlement.test.ts
  test/GPv2Signing.test.ts
  test/GPv2Trade.test.ts
  test/e2e/uniswapTrade.test.ts
Labels: merge when green

#489 Add Github-native dependabot configuration
  .github/dependabot.yml
  package.json
  test/e2e/zero-ex/v2/index.ts
  yarn.lock
Labels: merge when green

#505 Verify contracts on Tenderly
  README.md
  hardhat.config.ts
  package.json
  src/tasks/tenderly.ts
  src/workflows/deploy.sh
  yarn.lock
Labels: merge when green

#507 Remove hardhat imports from exported library code
  package.json
  src/ts/proxy.ts
  test/e2e/deployment.test.ts
Labels: merge when green

#508 Build lib with different options
  package.json
  tsconfig.json
  tsconfig.lib.commonjs.json
  tsconfig.lib.esm.json
Labels: merge when green

#509 Copy artifacts to `lib` and don't export build directory.
  hardhat.config.ts
  package.json
  src/tasks/artifacts.ts
  src/tasks/index.ts
  yarn.lock
Labels: merge when green

#510 Remove additional hardhat import in src/
  src/ts/deploy.ts
  src/ts/types/ethers.ts
Labels: merge when green, trivial

#511 Bump to alpha.14
  package.json
Labels: merge when green, trivial

#515 Non standard erc20 e2e test
  src/contracts/test/BalanceOf.sol
  src/contracts/test/NonStandardERC20.sol
  test/ERC20.ts
  test/GPv2SafeERC20.test.ts
  test/GPv2TradeExecution.test.ts
  test/e2e/nonStandardErc20.test.ts
Labels: merge when green

#503 Sign Order Cancellation
  src/ts/order.ts
  src/ts/sign.ts
  test/sign.test.ts
Labels: merge when green

#522 Bump version and remove imports for non-dependant packages
  package.json
  src/ts/order.ts
  src/ts/sign.ts
  src/ts/types/ethers.ts
Labels: trivial

#525 Upgrade to latest OZ SafeMath contracts
  package.json
  src/contracts/GPv2Settlement.sol
  yarn.lock
Labels: merge when green

#530 Revert OpenZepplin version bump
  package.json
  yarn.lock
Labels: merge when green, trivial

#529 Remove hardhat/console.sol dependency in test contract
  src/contracts/test/NonStandardERC20.sol
Labels: merge when green, trivial

#527 Add method for single transfer for swap fees
  src/contracts/libraries/GPv2Transfer.sol
  src/contracts/test/GPv2TransferTestInterface.sol
  test/GPv2Transfer.test.ts
Labels: balancer-v2

#528 Add vault relayer method for direct Balancer swaps
  src/contracts/GPv2VaultRelayer.sol
  src/contracts/interfaces/IVault.sol
  src/contracts/libraries/GPv2Transfer.sol
  src/contracts/test/GPv2TransferTestInterface.sol
  src/ts/index.ts
  src/ts/swap.ts
  test/GPv2Transfer.test.ts
  test/GPv2VaultRelayer.test.ts
Labels: balancer-v2

#537 Update vendored Vault artifact
  src/contracts/interfaces/IVault.sol
  test/e2e/balancer/.version
  test/e2e/balancer/Vault.json
Labels: trivial

#550 Refactor solver allow list
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/reader/AllowListStorageReader.sol
  src/ts/reader.ts
  test/AllowListStorageReader.test.ts
  test/GPv2AllowListAuthenticator.test.ts
Labels: merge when green

#549 Revert ERC20 transfers on non-contracts
  src/contracts/libraries/GPv2SafeERC20.sol
  test/GPv2SafeERC20.test.ts
  test/GPv2TradeExecution.test.ts
Labels: merge when green

#551 Vendor dependencies
  src/contracts/GPv2AllowListAuthentication.sol
  src/contracts/GPv2AllowanceManager.sol
  src/contracts/GPv2Settlement.sol
  src/contracts/interfaces/IERC20.sol
  src/contracts/libraries/GPv2Order.sol
  src/contracts/libraries/GPv2SafeERC20.sol
  src/contracts/libraries/GPv2Trade.sol
  src/contracts/libraries/GPv2TradeExecution.sol
  src/contracts/libraries/SafeMath.sol
  src/contracts/mixins/Initializable.sol
  src/contracts/mixins/ReentrancyGuard.sol
  src/contracts/mixins/StorageAccessible.sol
  src/contracts/test/ERC20Permit.sol
  src/contracts/test/ERC20PresetPermit.sol
  src/contracts/test/GPv2SafeERC20TestInterface.sol
  src/contracts/test/NonStandardERC20.sol
  src/contracts/test/vendor/ChiToken.sol
  test/GPv2AllowListAuthenticator.test.ts
  test/e2e/ercPermit.test.ts
Labels: merge when green

#553 Vendored Uniswap interfaces and libraries
  src/contracts/uniswap/IUniswapV2Factory.sol
  src/contracts/uniswap/IUniswapV2Pair.sol
  src/contracts/uniswap/UniswapV2Library.sol
Labels: trivial

#554 Refactor Uniswap library to enable mocked pairs for unit tests
  src/contracts/GPv2UniswapRouter.sol
  src/contracts/test/GPv2UniswapRouterTestInterface.sol
  src/contracts/uniswap/UniswapV2Library.sol
  test/GPv2UniswapRouter.test.ts
Labels: trivial

#560 Add GP Uniswap router benchmarks
  bench/uniswap/fixture.ts
  bench/uniswap/index.ts
Labels: merge when green

#567 Yarn upgrade
  package.json
  yarn.lock
Labels: trivial

#568 Use regular enum
  package.json
  src/ts/sign.ts
Labels: merge when green
